import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = 'http://localhost:4000/api';
const columns = ['To Do', 'In Progress', 'Done'];
const call = async (path, options = {}, token) => { const r = await fetch(API + path, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }); const body = await r.json(); if (!r.ok) throw new Error(body.error || 'Request failed'); return body; };

function Auth({ onLogin }) {
  const [mode, setMode] = useState('register'), [form, setForm] = useState({ name: '', username: '', mobile: '', email: '', password: '', role: 'member' }), [error, setError] = useState('');
  const submit = async e => { e.preventDefault(); setError(''); try { const data = await call(`/auth/${mode}`, { method: 'POST', body: JSON.stringify(form) }); localStorage.setItem('ipms-token', data.token); onLogin(data); } catch (e) { setError(e.message); } };
  return <main className="auth"><section className="auth-card"><div className="auth-heading"><div className="identity">◎</div><div><h1>{mode === 'login' ? 'Sign In' : 'Sign Up'}</h1><p>Welcome! Please <em>enter your details</em> to continue.</p></div></div><div className="rule"/><form onSubmit={submit}>{mode === 'register'&&<><label><span className="field-label">♟&nbsp; Name</span><input required placeholder="Enter your name" value={form.name} onChange={e=>setForm({...form,name:e.target.value,role:'member'})}/></label><label><span className="field-label">@&nbsp; Username</span><input required minLength="3" maxLength="30" placeholder="Choose a unique username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label><span className="field-label">☎&nbsp; Mobile number</span><input required type="tel" placeholder="Enter your mobile number" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/></label></>}<label><span className="field-label">✉&nbsp; Email</span><input required type="email" placeholder="Enter your email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="password"><span className="field-label">◉&nbsp; Password</span><input required minLength="6" type="password" placeholder="Minimum 6 characters" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error && <div className="error">{error}</div>}<button className="continue">↪&nbsp; {mode === 'login' ? 'Sign In' : 'Continue'}</button></form><div className="secure">♧&nbsp; Secure access to Production Studio</div><button className="link auth-switch" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode === 'login' ? 'Create an account' : 'Already registered? Sign in'}</button></section></main>;
}

function App() {
  const [session, setSession] = useState(null), [projects, setProjects] = useState([]), [users, setUsers] = useState([]), [active, setActive] = useState(null), [tasks, setTasks] = useState([]), [analytics, setAnalytics] = useState(null), [activity, setActivity] = useState([]), [tab, setTab] = useState('dashboard'), [showProject, setShowProject] = useState(false), [showTask, setShowTask] = useState(false), [sidebarOpen, setSidebarOpen] = useState(true), [profileOpen, setProfileOpen] = useState(false), [error, setError] = useState('');
  const token = session?.token || localStorage.getItem('ipms-token');
  const loadProjects = async () => { try { const [p,u] = await Promise.all([call('/projects',{},token),call('/users',{},token)]); setProjects(p); setUsers(u); if (!active && p[0]) setActive(p[0]); } catch { localStorage.removeItem('ipms-token'); setSession(null); } };
  useEffect(()=>{ if(token) loadProjects(); }, [session]);
  const loadProject = async () => { if (!active) return; const [t,a,l] = await Promise.all([call(`/projects/${active.id}/tasks`,{},token), call(`/projects/${active.id}/analytics`,{},token), call(`/projects/${active.id}/activity`,{},token)]); setTasks(t); setAnalytics(a); setActivity(l); };
  useEffect(()=>{ loadProject(); }, [active]);
  const changeStatus = async (task,status) => { await call(`/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify({status})},token); loadProject(); };
  if (!token || !session) return <Auth onLogin={setSession}/>;
  const createProject = async form => { try { const p=await call('/projects',{method:'POST',body:JSON.stringify(form)},token); setShowProject(false); setProjects([...projects,p]); setActive(p); } catch(e){setError(e.message);} };
  const createTask = async form => { try { await call(`/projects/${active.id}/tasks`,{method:'POST',body:JSON.stringify(form)},token); setShowTask(false); loadProject(); } catch(e){setError(e.message);} };
  const panelName = 'Production Studio';
  const menu = [['dashboard','▣','Dashboard'],['board','▤','My Tasks'],['projects','◈','Projects'],['team','♙','Team Members'],['analytics','▥','Analytics'],['activity','◉','Activity Log'],['ledger','♢','Blockchain Ledger'],['reports','▧','Reports']];
  const signOut = () => { localStorage.removeItem('ipms-token'); setSession(null); };
  return <div className={'shell dashboard-shell '+(!sidebarOpen?'sidebar-closed ':'')}><aside><div className="studio-mark">◉ <span>PRODUCTION<br/>STUDIO</span></div><div className="side-menu">{menu.map(([value,icon,label])=><button title={label} className={tab===value?'selected':''} onClick={()=>setTab(value)} key={label}>{icon}<span>{label}</span></button>)}</div><div className="account"><b>{session.user.name}</b><span>Member</span><button className="link" onClick={signOut}>⇥ Logout</button></div></aside><main className="workspace dashboard-workspace"><header className="topbar"><button className="sidebar-toggle" onClick={()=>setSidebarOpen(!sidebarOpen)} title={sidebarOpen?'Close navigation':'Open navigation'}>☰</button><b>Production Studio</b><div className="top-actions">◌ &nbsp; ◐ &nbsp; <button className="profile-button" onClick={()=>setProfileOpen(!profileOpen)} title="Profile"><i>{session.user.name.slice(0,1).toUpperCase()}</i>⌄</button>{profileOpen&&<section className="profile-menu"><b>{session.user.name}</b><span>{session.user.email}</span><small>Member</small><button onClick={signOut}>⇥ Sign out</button></section>}</div></header><section className="dashboard-title"><div><h1>Dashboard</h1><p>A centralized workspace for project management and collaboration.</p></div><button onClick={()=>setShowProject(true)}>+ New project</button></section>{error&&<div className="error">{error}</div>}{tab==='dashboard'&&<Dashboard projects={projects} tasks={tasks} analytics={analytics} activity={activity} onTasks={()=>setTab('board')} onProjects={()=>setShowProject(true)} onPanel={setTab}/>} {tab==='projects'&&<section className="project-list"><button onClick={()=>setShowProject(true)}>+ Create project</button>{projects.length?projects.map(p=><button className="project-row" onClick={()=>{setActive(p);setTab('board')}} key={p.id}>{p.name}<small>{p.description}</small></button>):<p>No projects created yet.</p>}</section>} {tab==='board'&&<><div className="content-action"><b>{active?.name || 'Select a project'}</b>{active&&<button onClick={()=>setShowTask(true)}>+ Create task</button>}</div>{active?<Board tasks={tasks} users={users} onChange={changeStatus}/>:<div className="empty">Create a project first.</div>}</>} {tab==='analytics'&&<Analytics data={analytics}/>} {tab==='activity'&&<Activity entries={activity}/>} {!['dashboard','projects','board','analytics','activity'].includes(tab)&&<UtilityPanel type={tab} projects={projects} users={users} tasks={tasks} activity={activity} analytics={analytics}/>}</main>{showProject&&<ProjectDialog users={users} onClose={()=>setShowProject(false)} onSave={createProject}/>} {showTask&&active&&<TaskDialog users={active.members} onClose={()=>setShowTask(false)} onSave={createTask}/>}</div>;
}
function Dashboard({projects,tasks,analytics,activity,onTasks,onProjects,onPanel}) { const values=[['▣','Total Projects',projects.length,'blue'],['▤','Tasks Progress',(analytics?.completion ?? 0)+'%','green'],['▥','Analytics',analytics?.risk || 'Low','orange'],['♙','Team Members',projects.reduce((n,p)=>n+p.members.length,0),'purple']]; return <section className="dash-grid"><div className="stat-row">{values.map(([icon,label,value,color])=><article className="dash-stat" key={label}><span className={color}>{icon}</span><div><small>{label}</small><b>{value}</b></div></article>)}</div><article className="dash-card overview"><h3>Project Overview</h3><div className="donut"><i/><b>{analytics?.completion ?? 0}%</b></div><div className="legend"><span><i className="blue"/> To do: {analytics?.todo ?? 0}</span><span><i className="green"/> In progress: {analytics?.inProgress ?? 0}</span><span><i className="purple"/> Completed: {analytics?.done ?? 0}</span></div></article><article className="dash-card status"><h3>Task Status</h3><div className="mini-bars">{['todo','inProgress','done','overdue'].map(key=><i key={key} style={{height:Math.max(12,(analytics?.[key]||0)*20)+'px'}}/>)}</div></article><article className="dash-card recent"><h3>Recent Activities</h3>{activity.slice(0,4).map(a=><p key={a.id}><i/> {a.detail}</p>)}{!activity.length&&<p><i/> No activities yet</p>}</article><article className="dash-card ledger"><h3>Blockchain Ledger</h3><div className="shield">♢</div><p>Secure, traceable activity records</p></article><article className="quick"><h3>Quick Access</h3><button onClick={onProjects}>◈ &nbsp; Projects</button><button onClick={onTasks}>▤ &nbsp; Tasks</button><button onClick={()=>onPanel('team')}>♙ &nbsp; Teams</button><button onClick={()=>onPanel('documents')}>▧ &nbsp; Documents</button><button onClick={()=>onPanel('reports')}>▥ &nbsp; Reports</button></article></section>}
function GuideDashboard({projects,analytics,activity}) { const cards=[['▣','My Projects',projects.length,'blue'],['▤','Tasks In Progress',analytics?.inProgress||0,'green'],['●','Tasks Completed',analytics?.done||0,'orange'],['♙','Team Members',projects.reduce((n,p)=>n+p.members.length,0),'purple']]; return <section className="guide-grid"><div className="guide-stat-row">{cards.map(([i,l,v,c])=><article className="guide-stat" key={l}><span className={c}>{i}</span><small>{l}</small><b>{v}</b></article>)}</div><article className="guide-card guide-projects"><h3>My Projects</h3><div className="guide-table"><span>Project Title</span><span>Start Date</span><span>Deadline</span><span>Status</span><span>Action</span></div>{projects.length?projects.map(p=><p key={p.id}>{p.name}</p>):<div className="no-content">▣<b>No projects found</b><small>You have not been assigned to any projects yet.</small></div>}</article><article className="guide-card guide-overview"><h3>Tasks Overview</h3><div className="guide-donut"/><div className="guide-legend"><p>● To Do</p><p>● In Progress</p><p>● Review</p><p>● Completed</p></div></article><article className="guide-card guide-mini"><h3>Upcoming Deadlines</h3><div className="no-content"><b>No upcoming deadlines</b><small>You have no upcoming deadlines.</small></div></article><article className="guide-card guide-mini"><h3>Recent Activity</h3><div className="no-content">{activity.length?<><b>{activity[0].detail}</b><small>Activity updates will appear here.</small></>:<><b>No recent activity</b><small>Activity updates will appear here.</small></>}</div></article><article className="guide-card guide-mini"><h3>AI Insights</h3><div className="no-content"><b>No insights available</b><small>AI insights and suggestions will appear here.</small></div></article></section>}
function AdminDashboard({projects,analytics,activity}) { const team=projects.reduce((n,p)=>n+p.members.length,0); const stats=[['▣','Total Projects',projects.length,'admin-blue'],['▤','Tasks In Progress',analytics?.inProgress||0,'admin-green'],['◉','Tasks Completed',analytics?.done||0,'admin-orange'],['♙','Team Members',team,'admin-purple']]; return <section className="admin-grid"><div className="admin-stat-row">{stats.map(([icon,label,value,color])=><article key={label} className="admin-stat"><span>{icon}</span><small>{label}</small><b>{value}</b><i className={color}/></article>)}</div><article className="admin-card admin-overview"><h3>Project Overview</h3><div className="admin-donut"><i/><i/><i/></div></article><article className="admin-card admin-status"><h3>Task Status</h3><div className="rainbow-bars">{[1,2,3,4,5].map(n=><i key={n} style={{height:(36+n*7)+'px'}}/>)}</div></article><article className="admin-card admin-recent"><h3>Recent Activities</h3>{activity.slice(0,4).map(a=><p key={a.id}>{a.detail}</p>)}{!activity.length&&[1,2,3,4].map(n=><p key={n}/>)}</article><article className="admin-card performance"><h3>Team Performance</h3><div/></article><article className="admin-card admin-ledger"><h3>Blockchain Ledger</h3><b>♢</b></article></section>}
function UtilityPanel({type,projects,users,tasks,activity,analytics}) { const labels={team:'Team Members',students:'Student Panel',guides:'Guide Panel',ledger:'Blockchain Ledger',reports:'Reports',review:'Task Review',insights:'AI Insights',messages:'Messages',calendar:'Calendar',documents:'Documents'}; const title=labels[type]||'Workspace'; if(type==='ledger') return <section className="utility"><h2>{title}</h2><Activity entries={activity}/></section>; if(type==='reports') return <section className="utility"><h2>{title}</h2><Analytics data={analytics||{completion:0,total:0,todo:0,inProgress:0,done:0,overdue:0,risk:'Low'}}/></section>; if(['team','students','guides'].includes(type)){const filtered=type==='students'?users.filter(u=>u.role==='member'):type==='guides'?users.filter(u=>u.role==='guide'):users; return <section className="utility"><h2>{title}</h2><div className="people">{filtered.length?filtered.map(u=><article key={u.id}><b>{u.name}</b><span>{u.email}</span><small>{u.role==='member'?'Student':u.role==='manager'?'Admin':u.role}</small></article>):<p>No users found.</p>}</div></section>;} if(type==='review') return <section className="utility"><h2>Task Review</h2><div className="review-list">{tasks.length?tasks.map(t=><article key={t.id}><b>{t.title}</b><span>{t.status} · {t.priority}</span></article>):<p>No tasks available for review.</p>}</div></section>; if(type==='insights') return <section className="utility"><h2>AI Insights</h2><div className="insight-card"><b>Project risk: {analytics?.risk||'Low'}</b><p>{analytics?.overdue ? `${analytics.overdue} outstanding task(s) are overdue. Review task deadlines.` : 'No overdue tasks detected. Continue monitoring progress.'}</p></div></section>; if(type==='calendar') return <section className="utility"><h2>Calendar</h2><div className="review-list">{tasks.filter(t=>t.dueDate).length?tasks.filter(t=>t.dueDate).map(t=><article key={t.id}><b>{new Date(t.dueDate).toLocaleDateString()}</b><span>{t.title}</span></article>):<p>No task deadlines have been added.</p>}</div></section>; if(type==='messages') return <section className="utility"><h2>Messages</h2><div className="empty">No messages yet.</div></section>; return <section className="utility"><h2>Documents</h2><div className="empty">No project documents have been added.</div></section>}
function Board({tasks,users,onChange}) { return <div className="board">{columns.map(col=><section className="column" key={col} onDragOver={e=>e.preventDefault()} onDrop={e=>onChange(JSON.parse(e.dataTransfer.getData('task')),col)}><h2>{col}<span>{tasks.filter(t=>t.status===col).length}</span></h2>{tasks.filter(t=>t.status===col).map(t=><article className="task" draggable onDragStart={e=>e.dataTransfer.setData('task',JSON.stringify(t))} key={t.id}><div className={'priority '+t.priority.toLowerCase()}>{t.priority}</div><h3>{t.title}</h3>{t.description&&<p>{t.description}</p>}<footer><span>{users.find(u=>u.id===t.assigneeId)?.name || 'Unassigned'}</span><span>{t.dueDate ? new Date(t.dueDate).toLocaleDateString() : 'No deadline'}</span></footer></article>)}</section>)}</div> }
function Analytics({data}) { if(!data)return null; return <section className="analytics"><div className="metric"><span>Completion</span><strong>{data.completion}%</strong><div className="bar"><i style={{width:data.completion+'%'}}/></div></div>{[['Total tasks',data.total],['To do',data.todo],['In progress',data.inProgress],['Completed',data.done],['Overdue',data.overdue],['Predicted risk',data.risk]].map(([l,v])=><div className="metric small" key={l}><span>{l}</span><strong className={l==='Predicted risk'?'risk '+String(v).toLowerCase():''}>{v}</strong></div>)}<p className="insight">Predictive insight: risk is based on outstanding overdue tasks and high-priority work.</p></section> }
function Activity({entries}) { return <section className="activity">{entries.length===0?<p>No activity recorded yet.</p>:entries.map(e=><article key={e.id}><span className="dot"/><div><b>{e.userName}</b> {e.action}: {e.detail}<small>{new Date(e.createdAt).toLocaleString()} · Ledger hash {e.hash.slice(0,12)}…</small></div></article>)}</section> }
function ProjectDialog({users,onClose,onSave}) { const [f,setF]=useState({name:'',description:'',memberIds:[]}); return <Modal title="New project" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(f)}}><label>Project name<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Description<textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><label>Team members<select multiple value={f.memberIds} onChange={e=>setF({...f,memberIds:[...e.target.selectedOptions].map(o=>o.value)})}>{users.map(u=><option value={u.id} key={u.id}>{u.name} ({u.role})</option>)}</select></label><button>Create project</button></form></Modal> }
function TaskDialog({users,onClose,onSave}) { const [f,setF]=useState({title:'',description:'',assigneeId:'',priority:'Medium',dueDate:''}); return <Modal title="Create task" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(f)}}><label>Task title<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><label>Description<textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><label>Assign to<select value={f.assigneeId} onChange={e=>setF({...f,assigneeId:e.target.value})}><option value="">Unassigned</option>{users.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label><label>Priority<select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}><option>High</option><option>Medium</option><option>Low</option></select></label><label>Deadline<input type="date" value={f.dueDate} onChange={e=>setF({...f,dueDate:e.target.value})}/></label><button>Create task</button></form></Modal> }
function Modal({title,onClose,children}) {return <div className="modal-bg"><section className="modal"><button className="close" onClick={onClose}>×</button><h2>{title}</h2>{children}</section></div>}
createRoot(document.getElementById('root')).render(<App/>);
